export const experienceData = [
  {
    id: 1,
    title: "Mechanic Intern",
    position: "Mechanic",
    company: "Asco Daihatsu",
    place: "South Jakarta",
    period: "May 2017 - July 2017",
    color: "border-accent",
    responsibilities: [
      "Assisted senior mechanics in routine vehicle inspections and repairs.",
      "Performed basic maintenance tasks such as oil changes and tire checks.",
      "Documented service records and reported issues to supervisors.",
    ],
  },
  {
    id: 2,
    title: "Operation Production",
    position: "Production Control",
    company: "PT Astra Honda Motor",
    place: "North Jakarta",
    period: "April 2018 - April 2020",
    color: "border-accent",
    responsibilities: [
      "Operated and monitored production line machinery to ensure smooth workflow.",
      "Maintained records of daily production output.",
      "Collaborated with team members to meet quality and safety standards.",
    ],
  },
  {
    id: 3,
    title: "Freelance",
    position: "Sales & Customer Engagement",
    company: "HD Group",
    place: "Remote",
    period: "February 2022 - November 2022 ",
    color: "border-accent",
    responsibilities: [
      "Promoted products through social media and digital channels.",
      "Engaged with customers to provide product information and support.",
      "Contributed to increasing awareness and sales for small business products.",
    ],
  },
  {
    id: 4,
    title: "Work Placement",
    position: "Web Developer",
    company: "TB Saluyu Mekar",
    place: "Kuningan",
    period: "April 2023 - July 2023",
    color: "border-accent",
    responsibilities: [
      "Collaborated with a 4-member team to build a stock management website.",
      "Developed basic features such as input, update, and reporting functions.",
      "Documented system processes and user instructions.",
    ],
  },
  {
    id: 5,
    title: "Freelance",
    position: "Testnet & Lightnode Operator",
    company: "WEB3 Crypto Community",
    place: "Remote",
    period: "April 2023 - February 2024",
    color: "border-accent",
    responsibilities: [
      "Participated in blockchain testnet programs by running validator and lightnode setups.",
      "Reported bugs and provided feedback to improve network stability.",
      "Maintained technical documentation for setup and troubleshooting.",
    ],
  },
  {
    id: 6,
    title: "Capstone Project",
    position: "Mobile Application Development",
    company: "Crypto Community",
    place: "Remote",
    period: "February 2024 - November 2024",
    color: "border-accent",
    responsibilities: [
      "Designed and developed a mobile application prototype for crypto-related use cases.",
      "Collaborated with peers to integrate blockchain-based features.",
      "Conducted testing and improved application based on feedback.",
    ],
  },
  {
    id: 7,
    title: "Pre launch Initiative",
    position: "Deputy Secretary",
    company: "KPCPN",
    place: "Kuningan",
    period: "July 2025 - Present",
    color: "border-accent",
    responsibilities: [
      "Prepared administrative reports and documentation for cooperative activities.",
      "Inputted and organized member data from multiple villages.",
      "Drafted proposals and financial budget plans (RAB) for initial programs.",
      "Coordinated with the Chairman and team during preparation meetings.",
    ],
  },
];
