import { Place } from "@mui/icons-material";

export const experienceData = [
  {
    id: 1,
    title: "Mechanic Intern",
    company: "Asco Daihatsu",
    place: "South Jakarta",
    period: "2017",
    color: "border-accent",
    //  responsibilities: [""],
  },
  {
    id: 2,
    title: "Operation Production",
    company: "PT Astra Honda Motor",
    place: "North Jakarta",
    period: "2018 - 2020",
    color: "border-accent",
    //  responsibilities: [""],
  },
  {
    id: 3,
    title: "Internship Admin Project",
    company: "Web Development TB Saluyu Mekar",
    place: "Kuningan",
    period: "2023",
    color: "border-accent",
    //  responsibilities: [""],
  },
  {
    id: 4,
    title: "Freelance Admin Marketing",
    company: "HD Group",
    place: "Kuningan",
    period: "2023",
    color: "border-accent",
    //  responsibilities: [""],
  },
  {
    id: 5,
    title: "Testnet Participan",
    company: "Crypto Community",
    place: "Kuningan",
    period: "2024",
    color: "border-accent",
    //  responsibilities: [""],
  },
  {
    id: 6,
    title: "Lightnode Operator",
    company: "Crypto Community",
    place: "Kuningan",
    period: "2024",
    color: "border-accent",
    //  responsibilities: [""],
  },
  {
    id: 7,
    title: "Secretary Deputy",
    company: "KPCPN Pra Launch",
    place: "Kuningan",
    period: "2025",
    color: "border-accent",
    //  responsibilities: [""],
  },
];
