export const experienceData = [
  {
    id: 1,
    title: "Internship (PKL)",
    position: "Mechanic",
    company: "Asco Daihatsu",
    place: "South Jakarta",
    period: "May 2017 - July 2017",
    color: "border-accent",
    responsibilities: [
      "Assisted in routine vehicle inspections and repairs.",
      "Performed basic maintenance such as oil changes and tire checks.",
      "Recorded service activities under supervisor guidance.",
    ],
  },
  {
    id: 2,
    title: "Operation Production",
    position: "Production Control",
    company: "PT Astra Honda Motor",
    place: "North Jakarta",
    period: "April 2018 - April 2020",
    color: "border-accent",
    responsibilities: [
      "Operated and monitored production line machines.",
      "Recorded daily production output.",
      "Worked with team to maintain quality and safety standards.",
    ],
  },
  {
    id: 3,
    title: "Freelance",
    position: "Sales & Customer Engagement",
    company: "HD Group",
    place: "Remote",
    period: "February 2022 - November 2022 ",
    color: "border-accent",
    responsibilities: [
      "Promoted products through social media.",
      "Provided product information and customer support.",
      "Helped increase awareness and sales of small business products.",
    ],
  },
  {
    id: 4,
    title: "Work Placement",
    position: "Web Developer",
    company: "TB Saluyu Mekar",
    place: "Kuningan",
    period: "April 2023 - July 2023",
    color: "border-accent",
    responsibilities: [
      "Collaborated with 4-member team to build a stock management website.",
      "Developed input, update, and reporting features.",
      "Created UI/UX design and user documentation.",
    ],
  },
  {
    id: 5,
    title: "Freelance",
    position: "Testnet & Lightnode Operator",
    company: "WEB3 Crypto Community",
    place: "Remote",
    period: "April 2023 - February 2024",
    color: "border-accent",
    responsibilities: [
      "Ran validator and lightnode for blockchain testnet programs.",
      "Reported bugs and provided feedback for network testing.",
      "Documented setup and troubleshooting steps.",
    ],
  },
  {
    id: 6,
    title: "Capstone Project",
    position: "Mobile App Developer",
    company: "Rumah Bunga Rosse",
    place: "Kuningan",
    period: "February 2024 - November 2024",
    color: "border-accent",
    responsibilities: [
      "Developed a CNN-based system to classify Aglaonema plant types.",
      "Preprocessed image dataset and trained deep learning model.",
      "Evaluated model accuracy and created user documentation.",
    ],
  },
  {
    id: 7,
    title: "Pre launch Initiative",
    position: "Deputy Secretary",
    company: "KPCPN",
    place: "Kuningan",
    period: "July 2025 - Present",
    color: "border-accent",
    responsibilities: [
      "Prepared administrative reports and cooperative documents.",
      "Organized member data from multiple villages.",
      "Drafted proposals and initial financial budget plans.",
      "Assisted coordination in preparation meetings.",
    ],
  },
];
