import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import LoadingSpinner from "@/components/LoadingSpinner";
import StairTransition from "@/components/StairTransition";
import MovingLights from "@/components/effects/MovingLights";
import AnimatedGrid from "@/components/effects/AnimatedGrid";
import GridBackground from "@/components/effects/GridBackground";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Create Next App",
  metadataBase: new URL("https://sukuna41.github.io"),
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable + " body-grid-background"}>
        {/* Tambahkan light spots */}
        <div className="light-spot light-spot-1"></div>
        <div className="light-spot light-spot-2"></div>
        <div className="light-spot light-spot-3"></div>

        <div className="content-layer">
          <Header />
          <GridBackground></GridBackground>
          <AnimatedGrid></AnimatedGrid>
          <MovingLights></MovingLights>
          <LoadingSpinner>{children}</LoadingSpinner>
          <StairTransition>{children}</StairTransition>
          <PageTransition>{children}</PageTransition>
        </div>
      </body>
    </html>
  );
}
