import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import Header from "@/components/Header";
import ScrollHandler from "../components/ScrollHandler";
import PageTransition from "@/components/PageTransition";
import LoadingSpinner from "../components/LoadingSpinner";
import StairTransition from "@/components/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Create Next App",
  metadataBase: new URL("https://sukuna41.github.io"),
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        <ScrollHandler>{children}</ScrollHandler>
        <LoadingSpinner>{children}</LoadingSpinner>
        {/* <StairTransition /> */}
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
