name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ganti dengan nama branch Anda jika berbeda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          # Tambahkan perintah build Anda di sini
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Menggunakan token yang telah dibuat
          publish_dir: ./out # Ganti dengan direktori output build Anda
